#!/usr/bin/python
from Adafruit_MotorHAT import Adafruit_MotorHAT, Adafruit_DCMotor

import time
import atexit

# create a default object, no changes to I2C address or frequency
mh = Adafruit_MotorHAT(addr=0x60)

################################# DC motor test!
leftMotor = mh.getMotor(1)
rightMotor = mh.getMotor(2)

# set the speed to start, from 0 (off) to 255 (max speed)
leftMotor.setSpeed(150)
rightMotor.setSpeed(150)
leftMotor.run(Adafruit_MotorHAT.FORWARD);
rightMotor.run(Adafruit_MotorHAT.FORWARD);
# turn on motor
leftMotor.run(Adafruit_MotorHAT.RELEASE);
rightMotor.run(Adafruit_MotorHAT.RELEASE);

leftMotor.run(Adafruit_MotorHAT.FORWARD)
rightMotor.run(Adafruit_MotorHAT.FORWARD)

for i in reversed(range(50,75)):
	leftMotor.setSpeed(i)
	rightMotor.setSpeed(i)
	time.sleep(0.01)
	
	

